apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: mysql-source
  namespace: data
  labels:
    strimzi.io/cluster: connect-a
  annotations:
    kbeacon.io/discovery-mode: hybrid
    kbeacon.io/owner-team: data-platform
    kbeacon.io/criticality: high
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    database.hostname: mysql.prod.svc.cluster.local
    database.port: 3306
    database.user: debezium
    database.password: ${secrets:data/mysql-source-db:password}
