global:
  external_labels:
    cluster: prod-eu-1
    environment: prod
    region: eu

remote_write:
  - url: https://mimir.example.com/api/v1/push
    headers:
      X-Scope-OrgID: platform-prod
    queue_config:
      capacity: 10000
      max_shards: 50
      min_shards: 1
      max_samples_per_send: 2000
    metadata_config:
      send: true
