
{{- if .Values.config.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kbeacon.configMapName" . }}
  labels:
    {{- include "kbeacon.labels" . | nindent 4 }}
data:
  config.yaml: |
    apiVersion: kbeacon.io/v1alpha1
    kind: AgentConfig
    cluster:
      name: {{ required "cluster.name is required" .Values.cluster.name | quote }}
      environment: {{ .Values.cluster.environment | quote }}
      region: {{ .Values.cluster.region | quote }}
    log:
      level: {{ .Values.log.level | quote }}
    agent:
      http:
        port: {{ .Values.agent.http.port }}
      shutdownGracePeriod: {{ .Values.agent.shutdownGracePeriod | quote }}
    discovery:
{{ toYaml .Values.discovery | indent 6 }}
    resourcesToWatch:
{{ toYaml .Values.resourcesToWatch | indent 6 }}
    metrics:
      edge:
        enabled: {{ .Values.metrics.edge.enabled }}
      runtime:
        enabled: {{ .Values.metrics.runtime.enabled }}
{{- end }}
