apiVersion: v1
kind: Namespace
metadata:
  name: payments
  labels:
    app.kubernetes.io/part-of: kbeacon-demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: reports
  labels:
    app.kubernetes.io/part-of: kbeacon-demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: shared
  labels:
    app.kubernetes.io/part-of: kbeacon-demo
