apiVersion: v1
kind: Secret
metadata:
  name: payments-db
  namespace: payments
  annotations:
    kbeacon.io/owner-team: payments-platform
    kbeacon.io/criticality: critical
type: Opaque
stringData:
  username: demo
  password: demo
---
apiVersion: v1
kind: Secret
metadata:
  name: stripe-api
  namespace: payments
  annotations:
    kbeacon.io/owner-team: payments-platform
    kbeacon.io/criticality: high
type: Opaque
stringData:
  token: demo
---
apiVersion: v1
kind: Secret
metadata:
  name: platform-ca
  namespace: shared
  annotations:
    kbeacon.io/owner-team: platform
    kbeacon.io/criticality: high
type: Opaque
stringData:
  ca.crt: demo
