
image:
  repository: kbeacon-agent
  tag: dev
  pullPolicy: IfNotPresent

cluster:
  name: minikube
  environment: local

log:
  level: debug

agent:
  http:
    port: 8080
  shutdownGracePeriod: 15s

discovery:
  defaultMode: hybrid
  includeImagePullSecrets: true
  includeInitContainers: true
  includeEphemeralContainers: true
  readPodTemplateAnnotations: true
  namespaces:
    include:
      - kbeacon-demo
    exclude: []
  resyncInterval: 10h
  reconcile:
    debounce: 250ms

resourcesToWatch:
  core:
    secrets: true
    pods: false
  apps:
    deployments: true
    statefulSets: false
    daemonSets: false
  batch:
    jobs: false
    cronJobs: false

metrics:
  runtime:
    enabled: true

service:
  type: ClusterIP
  port: 8080

serviceMonitor:
  enabled: false

rbac:
  create: true
  scope: cluster

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
