
apiVersion: v2
name: kbeacon
description: Kubernetes-native Secret Dependency Intelligence Agent for Prometheus, Grafana, and Mimir
type: application
version: 0.3.0
appVersion: "0.3.0"
home: https://github.com/memoliyasti/kbeacon
sources:
  - https://github.com/memoliyasti/kbeacon
keywords:
  - kubernetes
  - secrets
  - prometheus
  - grafana
  - mimir
  - observability
maintainers:
  - name: KBeacon Maintainers
    email: mehmetyasti23@gmail.com
annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/license: MIT
  artifacthub.io/signKey: |
    fingerprint: 4A140B3665CEC3173C9504BAA6A804C3C4B7158E
    url: https://memoliyasti.github.io/kbeacon/charts/kbeacon-helm-signing-key.asc
