
nameOverride: ""
fullnameOverride: ""

image:
  repository: ghcr.io/memoliyasti/kbeacon
  tag: "0.2.2"
  digest: ""
  pullPolicy: IfNotPresent

replicaCount: 1

imagePullSecrets: []

cluster:
  name: ""
  environment: ""
  region: ""

log:
  level: info

config:
  create: true
  existingConfigMap: ""

agent:
  http:
    port: 8080
  shutdownGracePeriod: 15s

health:
  livenessPath: /healthz
  readinessPath: /readyz

discovery:
  defaultMode: hybrid
  includeImagePullSecrets: true
  includeInitContainers: true
  includeEphemeralContainers: true
  readPodTemplateAnnotations: true
  metadataLabels:
    enabled: true
    ownerTeam:
      - app.kubernetes.io/team
      - team
      - owner-team
      - ownerTeam
      - technical-owner
      - technicalOwner
      - business-owner
      - businessOwner
    service:
      - app.kubernetes.io/name
      - app
      - service
      - service-name
      - serviceName
    environment:
      - app.kubernetes.io/environment
      - environment
      - env
      - stage
    criticality:
      - app.kubernetes.io/criticality
      - criticality
      - priority
      - tier
      - slo-tier
  namespaces:
    include: []
    exclude:
      - kube-system
      - kube-public
      - kube-node-lease
  resyncInterval: 10h
  reconcile:
    debounce: 250ms

resourcesToWatch:
  core:
    secrets: true
    pods: true
  apps:
    deployments: true
    statefulSets: true
    daemonSets: true
  batch:
    jobs: true
    cronJobs: true

metrics:
  edge:
    enabled: true
  runtime:
    enabled: true

service:
  type: ClusterIP
  port: 8080
  annotations: {}
  labels: {}

prometheus:
  scrapeAnnotations:
    enabled: false
    target: service
    path: /metrics
    port: "8080"

serviceMonitor:
  enabled: false
  labels: {}
  annotations: {}
  interval: 30s
  scrapeTimeout: 10s
  honorLabels: true
  metricRelabelings: []
  relabelings: []

rbac:
  create: true
  scope: cluster
  extraRules: []

serviceAccount:
  create: true
  name: ""
  annotations: {}

dashboards:
  enabled: false
  labels:
    grafana_dashboard: "1"
  annotations: {}

networkPolicy:
  enabled: false
  ingress:
    from: []

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  fsGroup: 65532

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

nodeSelector: {}
tolerations: []
affinity: {}
priorityClassName: ""
podAnnotations: {}
podLabels: {}
extraArgs: []
extraEnv: []
extraVolumes: []
extraVolumeMounts: []
