
nameOverride: ""
fullnameOverride: ""

image:
  repository: ghcr.io/memoliyasti/kbeacon
  tag: "0.1.2"
  digest: ""
  pullPolicy: IfNotPresent

replicaCount: 1

imagePullSecrets: []

cluster:
  name: ""
  environment: ""
  region: ""

log:
  level: info

config:
  create: true
  existingConfigMap: ""

agent:
  http:
    port: 8080
  shutdownGracePeriod: 15s

health:
  livenessPath: /healthz
  readinessPath: /readyz

discovery:
  defaultMode: hybrid
  includeImagePullSecrets: true
  includeInitContainers: true
  includeEphemeralContainers: true
  readPodTemplateAnnotations: true
  namespaces:
    include: []
    exclude:
      - kube-system
      - kube-public
      - kube-node-lease
  resyncInterval: 10h
  reconcile:
    debounce: 250ms

resourcesToWatch:
  core:
    secrets: true
    pods: true
  apps:
    deployments: true
    statefulSets: true
    daemonSets: true
  batch:
    jobs: true
    cronJobs: true

metrics:
  runtime:
    enabled: true

service:
  type: ClusterIP
  port: 8080
  annotations: {}
  labels: {}

serviceMonitor:
  enabled: false
  labels: {}
  annotations: {}
  interval: 30s
  scrapeTimeout: 10s
  metricRelabelings: []
  relabelings: []

rbac:
  create: true
  scope: cluster
  extraRules: []

serviceAccount:
  create: true
  name: ""
  annotations: {}

dashboards:
  enabled: false
  labels:
    grafana_dashboard: "1"
  annotations: {}

networkPolicy:
  enabled: false
  ingress:
    from: []

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  fsGroup: 65532

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

nodeSelector: {}
tolerations: []
affinity: {}
priorityClassName: ""
podAnnotations: {}
podLabels: {}
extraArgs: []
extraEnv: []
extraVolumes: []
extraVolumeMounts: []
